export const topics = [
  { id: '01', name: 'DOCKER',     sub: 'Containers',    icon: 'devicon-docker-plain colored',            slug: 'docker'      },
  { id: '02', name: 'KUBERNETES', sub: 'Orchestration', icon: 'devicon-kubernetes-plain colored',        slug: 'kubernetes'  },
  { id: '03', name: 'AWS',        sub: 'Cloud',          icon: 'devicon-amazonwebservices-plain colored', slug: 'aws'         },
  { id: '04', name: 'CI/CD',      sub: 'Pipelines',      icon: 'fas fa-code-branch', iconStyle: { fontSize: '2rem' }, slug: 'cicd' },
  { id: '05', name: 'TERRAFORM',  sub: 'IaC',            icon: 'devicon-terraform-plain colored',        slug: 'terraform'   },
  { id: '06', name: 'ANSIBLE',    sub: 'Automation',     icon: 'devicon-ansible-plain',                  slug: 'ansible'     },
  { id: '07', name: 'LINUX',      sub: 'Foundation',     icon: 'devicon-linux-plain',                    slug: 'linux'       },
  { id: '08', name: 'MONITORING', sub: 'Observability',  icon: 'devicon-prometheus-original', iconStyle: { color: '#e6522c' }, slug: 'monitoring' },
  { id: '09', name: 'SCRIPTING',  sub: 'Automation',     icon: 'fas fa-terminal',                        slug: 'scripting'   },
]

export const episodes = [
  {
    num: '01',
    tag: 'DOCKER',
    tagIcon: 'devicon-docker-plain colored',
    title: 'Dockerfile Tutorial: Best Practices for 2026',
    desc: 'Learn how to build multi-stage Dockerfile and how to minimize image size.',
    platform: 'yt',
    platformLabel: 'YOUTUBE',
    platformIcon: 'fab fa-youtube',
    date: 'Apr 5, 2026',
    url: 'https://youtu.be/grycki9EjW8?si=L6j6riR4F4nrlOvJ',
    thumbnail: 'https://img.youtube.com/vi/grycki9EjW8/hqdefault.jpg',
  },
  {
    num: '02',
    tag: 'DOCKER',
    tagIcon: 'devicon-docker-plain colored',
    title: 'Building Multi-Platform Docker Images and Fast Caching',
    desc: 'Learn how to build Docker images for multiple platforms (amd64 + arm64) using Buildx.',
    platform: 'yt',
    platformLabel: 'YOUTUBE',
    platformIcon: 'fab fa-youtube',
    date: 'Apr 21, 2026',
    url: 'https://youtu.be/OcnPKTux_tA?si=J76EZ3cPQykSuQIE',
    thumbnail: 'https://img.youtube.com/vi/OcnPKTux_tA/hqdefault.jpg',
  }
]

export const platforms = [
  {
    key: 'yt',
    name: 'YOUTUBE',
    icon: 'fab fa-youtube',
    iconColor: '#ff3333',
    handle: '@devops_unfiltered',
    handleIcon: 'fas fa-at',
    stats: [
      { icon: 'fas fa-film',    label: 'Long-form' },
      { icon: 'fas fa-wifi',    label: 'Live sessions' },
    ],
    desc: 'Hands-on videos — production-grade from the first minute. No padding, no filler.',
    typeIcon: 'fas fa-circle-play',
    typeLabel: 'Full tutorials + Live',
    url: 'https://www.youtube.com/@devops_unfiltered',
  },
  {
    key: 'ig',
    name: 'INSTAGRAM',
    icon: 'fab fa-instagram',
    iconColor: '#e1306c',
    handle: '@devopsunfiltered',
    handleIcon: 'fas fa-at',
    stats: [
      { icon: 'fas fa-mobile-screen', label: 'Reels' },
      { icon: 'fas fa-images',         label: 'Carousels' },
    ],
    desc: 'Dense, fast content — a 90-second Reel that covers more than most blog posts.',
    typeIcon: 'fas fa-bolt',
    typeLabel: 'Daily Reels + Carousels',
    url: 'https://www.instagram.com/devopsunfiltered/?hl=en',
  },
  {
    key: 'li',
    name: 'LINKEDIN',
    icon: 'fab fa-linkedin',
    iconColor: '#0077b5',
    handle: 'Ashraf | DevOps Engineer',
    handleIcon: 'fas fa-user-tie',
    stats: [
      { icon: 'fas fa-file-lines', label: 'Articles' },
      { icon: 'fas fa-briefcase',  label: 'Career tips' },
    ],
    desc: 'Deep analysis, personal experience, and honest advice for engineers job hunting in DevOps.',
    typeIcon: 'fas fa-pen-nib',
    typeLabel: 'Technical articles',
    url: 'https://www.linkedin.com/in/ashraf-mheidat-8471b9294',
  },
]

export const contactLinks = [
  { icon: 'fas fa-envelope',  iconColor: '#a35a10', text: 'devopsunfiltered@gmail.com', label: 'Collabs & general inquiries', href: 'mailto:devopsunfiltered@gmail.com' },
  { icon: 'fab fa-instagram', iconColor: '#e1306c', text: '@devopsunfiltered',           label: 'DM on Instagram',            href: 'https://www.instagram.com/devopsunfiltered/?hl=en' },
  { icon: 'fab fa-linkedin',  iconColor: '#0077b5', text: 'Ashraf | DevOps Engineer',     label: 'Connect on LinkedIn',        href: 'https://www.linkedin.com/in/ashraf-mheidat-8471b9294' },
]

export const toolDetails = {
  docker: {
    slug: 'docker',
    name: 'DOCKER',
    sub: 'Containers',
    icon: 'devicon-docker-plain colored',
    tagline: 'Build once. Run anywhere. No more "works on my machine."',
    what: 'Docker is an open-source platform that packages your application and all its dependencies into a lightweight, portable unit called a container. Unlike virtual machines, containers share the host OS kernel — making them fast to start and resource-efficient. Docker is the foundation of modern DevOps: if you deploy software, you need to understand containers.',
    benefits: [
      { icon: 'fas fa-equals',       title: 'Consistency',       desc: 'The same container image runs identically in development, staging, and production. No more environment-specific bugs.' },
      { icon: 'fas fa-bolt',         title: 'Fast Startup',      desc: 'Containers start in milliseconds, not minutes. Spin up and tear down entire environments instantly.' },
      { icon: 'fas fa-feather',      title: 'Lightweight',       desc: 'Containers share the host kernel — no full OS per application. Run dozens of containers on a single machine.' },
      { icon: 'fas fa-ship',         title: 'Portability',       desc: 'Build on a Mac, run on Linux, deploy to Kubernetes, push to any cloud. One image, any target.' },
      { icon: 'fas fa-layer-group',  title: 'Layer Caching',     desc: 'Docker caches each image layer. Rebuild only what changed — faster CI pipelines, cheaper compute.' },
      { icon: 'fas fa-globe',        title: 'Huge Ecosystem',    desc: 'Docker Hub has 100k+ public images. Official images for every major database, runtime, and tool.' },
    ],
    concepts: [
      { term: 'Image',              def: 'A read-only template built from a Dockerfile. The blueprint for a container.' },
      { term: 'Container',          def: 'A running instance of an image. An isolated process with its own filesystem, network, and process space.' },
      { term: 'Dockerfile',         def: 'A text file with build instructions: FROM, RUN, COPY, CMD. Each instruction creates a cached layer.' },
      { term: 'Registry',           def: 'Storage and distribution for Docker images. Docker Hub is the public default; ECR and GHCR are common private alternatives.' },
      { term: 'Volume',             def: 'Persistent storage that survives container restarts. Mount host paths or managed Docker volumes.' },
      { term: 'Docker Compose',     def: 'A tool to define and run multi-container applications using a single YAML file.' },
      { term: 'Layer',              def: 'Each Dockerfile instruction creates an immutable cached layer. Layers are shared between images to save disk and bandwidth.' },
      { term: 'Multi-stage Build',  def: 'Use multiple FROM statements to build in one stage and copy only the final artifact to a lean production image.' },
    ],
    commands: [
      { cmd: 'docker build -t myapp:1.0 .', desc: 'Build an image from the Dockerfile in the current directory' },
      { cmd: 'docker run -d -p 8080:80 myapp:1.0', desc: 'Run a container in the background, map host port 8080 → container port 80' },
      { cmd: 'docker ps', desc: 'List all running containers' },
      { cmd: 'docker exec -it <id> bash', desc: 'Open an interactive shell inside a running container' },
      { cmd: 'docker logs -f <id>', desc: 'Stream logs from a running container' },
      { cmd: 'docker images', desc: 'List all local images with their sizes' },
      { cmd: 'docker push myrepo/myapp:1.0', desc: 'Push an image to a registry' },
      { cmd: 'docker compose up -d', desc: 'Start all services defined in docker-compose.yml in detached mode' },
    ],
  },

  kubernetes: {
    slug: 'kubernetes',
    name: 'KUBERNETES',
    sub: 'Orchestration',
    icon: 'devicon-kubernetes-plain colored',
    tagline: 'Run containers at scale. Automatically.',
    what: 'Kubernetes (K8s) is an open-source container orchestration platform originally built by Google. It automates deployment, scaling, and management of containerized applications across a cluster of machines. Where Docker runs a single container on a single host, Kubernetes manages thousands of containers across hundreds of machines — with built-in load balancing, self-healing, and zero-downtime deployments.',
    benefits: [
      { icon: 'fas fa-arrows-up-down',  title: 'Auto-scaling',       desc: 'Scale pods up or down automatically based on CPU, memory, or custom metrics. Handle traffic spikes without manual intervention.' },
      { icon: 'fas fa-heart-pulse',     title: 'Self-healing',       desc: 'K8s detects failed containers and restarts them automatically. If a node dies, pods are rescheduled on healthy nodes.' },
      { icon: 'fas fa-scale-balanced',  title: 'Load Balancing',     desc: 'Automatically distributes traffic across healthy pods. No manual load balancer configuration required.' },
      { icon: 'fas fa-rotate',          title: 'Rolling Deployments', desc: 'Deploy new versions with zero downtime. Roll back with a single command if something breaks.' },
      { icon: 'fas fa-key',             title: 'Config & Secrets',   desc: 'Manage configuration and sensitive data separately from your application code using ConfigMaps and Secrets.' },
      { icon: 'fas fa-layer-group',     title: 'Resource Management', desc: 'Set CPU and memory limits per container. The scheduler places workloads on nodes that have capacity.' },
    ],
    concepts: [
      { term: 'Pod',        def: 'The smallest deployable unit in K8s. One or more containers that share network and storage.' },
      { term: 'Deployment', def: 'Manages a set of identical Pods. Handles rolling updates, rollbacks, and scaling.' },
      { term: 'Service',    def: 'A stable network endpoint for a set of Pods. Types: ClusterIP, NodePort, LoadBalancer.' },
      { term: 'Namespace',  def: 'A virtual cluster within a cluster. Used to isolate workloads by environment or team.' },
      { term: 'ConfigMap',  def: 'Stores non-sensitive configuration as key-value pairs. Injected into containers as env vars or mounted files.' },
      { term: 'Secret',     def: 'Stores sensitive data (passwords, tokens) encoded in base64. Referenced by pods at runtime.' },
      { term: 'Ingress',    def: 'Manages external HTTP/HTTPS access to services. Acts as a reverse proxy and SSL terminator.' },
      { term: 'Node',       def: 'A physical or virtual machine in the cluster. Each node runs pods assigned by the scheduler.' },
    ],
    commands: [
      { cmd: 'kubectl apply -f deployment.yaml', desc: 'Apply a manifest file to the cluster' },
      { cmd: 'kubectl get pods -n production', desc: 'List all pods in the production namespace' },
      { cmd: 'kubectl describe pod <name>', desc: 'Get detailed info about a pod — events, status, resource usage' },
      { cmd: 'kubectl logs -f <pod-name>', desc: 'Stream logs from a running pod' },
      { cmd: 'kubectl exec -it <pod> -- bash', desc: 'Open an interactive shell inside a running container' },
      { cmd: 'kubectl scale deploy myapp --replicas=5', desc: 'Scale a deployment to 5 replicas manually' },
      { cmd: 'kubectl rollout undo deployment myapp', desc: 'Roll back to the previous deployment version' },
      { cmd: 'kubectl top nodes', desc: 'Show real-time CPU and memory usage per node' },
    ],
  },

  aws: {
    slug: 'aws',
    name: 'AWS',
    sub: 'Cloud',
    icon: 'devicon-amazonwebservices-plain colored',
    tagline: 'The cloud platform that runs the internet.',
    what: 'Amazon Web Services (AWS) is the world\'s most comprehensive cloud platform, offering 200+ fully featured services from data centers globally. From compute and storage to machine learning and IoT, AWS provides on-demand infrastructure you pay for only when you use it. For DevOps engineers, AWS is the operating environment — where containers run, pipelines deploy to, and logs land.',
    benefits: [
      { icon: 'fas fa-arrows-up-down', title: 'Elastic Scaling',   desc: 'Scale compute up and down in minutes. Auto Scaling Groups react to load automatically — pay only for what you use.' },
      { icon: 'fas fa-globe',          title: 'Global Reach',      desc: '33+ regions and 100+ availability zones worldwide. Deploy close to your users and build multi-region architectures.' },
      { icon: 'fas fa-server',         title: 'Managed Services',  desc: 'AWS patches RDS databases, EKS clusters, and caches so you focus on your application, not the infrastructure.' },
      { icon: 'fas fa-shield-halved',  title: 'Security & Compliance', desc: 'IAM, VPC, KMS, GuardDuty. Compliant with SOC 2, PCI-DSS, HIPAA, and 140+ other security standards.' },
      { icon: 'fas fa-puzzle-piece',   title: 'Deep Ecosystem',    desc: 'Every tool integrates with AWS: GitHub Actions deploys to ECS, Terraform provisions your VPC, Datadog reads CloudWatch.' },
      { icon: 'fas fa-dollar-sign',    title: 'Pay-as-you-go',     desc: 'No upfront costs. Spot and Reserved Instances cut costs 60–90% compared to on-demand pricing.' },
    ],
    concepts: [
      { term: 'EC2',        def: 'Elastic Compute Cloud. Virtual machines in the cloud. The foundation of most AWS compute workloads.' },
      { term: 'S3',         def: 'Simple Storage Service. Object storage for static assets, backups, logs, and Terraform state files.' },
      { term: 'VPC',        def: 'Virtual Private Cloud. Your isolated private network inside AWS — subnets, routing, security groups, NAT.' },
      { term: 'IAM',        def: 'Identity and Access Management. Controls who can do what in your account. Apply least-privilege principle strictly.' },
      { term: 'EKS',        def: 'Elastic Kubernetes Service. Managed Kubernetes — AWS runs the control plane, you run your workloads.' },
      { term: 'RDS',        def: 'Relational Database Service. Managed MySQL, PostgreSQL, Aurora with automated backups and failover.' },
      { term: 'Lambda',     def: 'Run code without managing servers. Event-driven, scales to zero. Pay per invocation, not per hour.' },
      { term: 'CloudWatch', def: 'AWS-native monitoring: metrics, logs, alarms, and dashboards. The default observability layer for all AWS services.' },
    ],
    commands: [
      { cmd: 'aws ec2 describe-instances --region us-east-1', desc: 'List all EC2 instances in a region' },
      { cmd: 'aws s3 cp file.tar.gz s3://my-bucket/', desc: 'Upload a file to an S3 bucket' },
      { cmd: 'aws eks update-kubeconfig --name my-cluster', desc: 'Configure kubectl to connect to an EKS cluster' },
      { cmd: 'aws sts get-caller-identity', desc: 'Verify which AWS identity you are currently authenticated as' },
      { cmd: 'aws logs tail /aws/lambda/myfunction --follow', desc: 'Stream Lambda function logs in real time' },
      { cmd: 'aws iam list-roles', desc: 'List all IAM roles in the account' },
    ],
  },

  cicd: {
    slug: 'cicd',
    name: 'CI/CD',
    sub: 'Pipelines',
    icon: 'fas fa-code-branch',
    iconStyle: { fontSize: '2rem' },
    tagline: 'Ship fast. Break nothing. Automate everything in between.',
    what: 'CI/CD stands for Continuous Integration and Continuous Delivery. CI is the practice of automatically building and testing code every time a developer pushes a change. CD is the automated delivery of that tested code to staging or production. Together, they eliminate manual release processes and shrink the time between writing code and running it in production — from weeks to minutes.',
    benefits: [
      { icon: 'fas fa-rocket',        title: 'Faster Releases',     desc: 'Automate the path from commit to production. Release multiple times per day instead of once per quarter.' },
      { icon: 'fas fa-bug',           title: 'Catch Bugs Early',    desc: 'Run tests on every push. Find failures when they are small, not days later buried in a big batch merge.' },
      { icon: 'fas fa-ban',           title: 'No Manual Steps',     desc: 'Humans make mistakes doing repetitive tasks. Pipelines do not. Automate builds, tests, scans, and deploys.' },
      { icon: 'fas fa-rotate',        title: 'Consistent Deploys',  desc: 'Every deployment follows the same automated process. No "it worked in my terminal" surprises.' },
      { icon: 'fas fa-shield-halved', title: 'Security Scanning',   desc: 'Embed SAST, dependency scanning, and container image scanning into the pipeline automatically on every PR.' },
      { icon: 'fas fa-gauge-high',    title: 'Faster Feedback',     desc: 'Developers know within minutes if their change broke something — not hours or days later in a code review.' },
    ],
    concepts: [
      { term: 'Pipeline',       def: 'A sequence of automated stages: build → test → scan → deploy. Triggered by a git event.' },
      { term: 'Stage',          def: 'A logical group of jobs. Stages run sequentially; jobs within a stage can run in parallel.' },
      { term: 'Job',            def: 'A single unit of work — running tests, building a Docker image, or deploying to a cluster.' },
      { term: 'Artifact',       def: 'Output from a stage (a binary, Docker image, test report) that is passed to the next stage.' },
      { term: 'Runner / Agent', def: 'The compute that executes pipeline jobs. Can be shared SaaS runners or self-hosted machines.' },
      { term: 'Environment',    def: 'A deployment target (dev, staging, prod). Environments can require manual approvals before deploy.' },
      { term: 'Trigger',        def: 'What starts a pipeline: a push, a merge request, a tag, a schedule, or an API call.' },
      { term: 'Rollback',       def: 'Automated reversion to a previously working version when a deployment fails health checks.' },
    ],
    commands: [
      { cmd: '# GitHub Actions trigger\non:\n  push:\n    branches: [main]', desc: 'Trigger pipeline on every push to main' },
      { cmd: 'docker build -t $IMAGE:$COMMIT_SHA .', desc: 'Tag images with the git commit SHA for full traceability' },
      { cmd: 'kubectl set image deploy/app app=$IMAGE:$TAG', desc: 'Rolling deploy to Kubernetes in a CD step' },
      { cmd: 'trivy image myapp:latest', desc: 'Scan container image for vulnerabilities inside the pipeline' },
      { cmd: 'terraform plan -out=tfplan && terraform apply tfplan', desc: 'Infrastructure changes gated behind a saved plan review' },
    ],
  },

  terraform: {
    slug: 'terraform',
    name: 'TERRAFORM',
    sub: 'Infrastructure as Code',
    icon: 'devicon-terraform-plain colored',
    tagline: 'Your infrastructure is code. Version it, review it, apply it.',
    what: 'Terraform by HashiCorp is the industry-standard Infrastructure as Code (IaC) tool. You describe your infrastructure — VPCs, EC2 instances, databases, DNS records — in declarative HCL configuration files. Terraform generates an execution plan, shows you exactly what will change, and applies those changes across any cloud provider. Infrastructure that was once tribal knowledge becomes a versioned, reviewable, testable codebase.',
    benefits: [
      { icon: 'fas fa-code-branch', title: 'Version Control',   desc: 'Infrastructure lives in Git. Every change is tracked, reviewed in a PR, and fully reversible.' },
      { icon: 'fas fa-cloud',       title: 'Multi-cloud',       desc: 'Provision AWS, Azure, GCP, and 3000+ other providers with the same workflow and tooling.' },
      { icon: 'fas fa-eye',         title: 'Plan Before Apply', desc: 'terraform plan shows exactly what will be created, changed, or destroyed — before touching anything real.' },
      { icon: 'fas fa-cube',        title: 'Reusable Modules',  desc: 'Package infrastructure patterns as modules. Reuse a VPC module across every project with different inputs.' },
      { icon: 'fas fa-database',    title: 'State Management',  desc: 'Terraform tracks the real state of your infrastructure. It knows what exists and what needs to change.' },
      { icon: 'fas fa-equals',      title: 'Idempotent',        desc: 'Run terraform apply 100 times — same result every time. Only real differences trigger API calls.' },
    ],
    concepts: [
      { term: 'Provider',     def: 'A plugin that talks to an external API (AWS, GitHub, K8s). Translates HCL resources into API calls.' },
      { term: 'Resource',     def: 'A single infrastructure object: an EC2 instance, an S3 bucket, a DNS record, a Kubernetes namespace.' },
      { term: 'State',        def: 'A JSON file that maps your config to real-world infrastructure. Store remotely in S3 + DynamoDB locking.' },
      { term: 'Module',       def: 'A reusable package of Terraform configuration with input variables and output values.' },
      { term: 'Variable',     def: 'Input parameters for your configuration. Pass values via .tfvars files or environment variables.' },
      { term: 'Output',       def: 'Values exported after apply — like an EC2 IP — available to other modules or displayed in the terminal.' },
      { term: 'Data Source',  def: 'Look up existing infrastructure not managed by Terraform: an AMI ID, a VPC ID, a Route53 zone.' },
      { term: 'Backend',      def: 'Where Terraform state is stored. Remote backends (S3, Terraform Cloud) enable safe team collaboration.' },
    ],
    commands: [
      { cmd: 'terraform init', desc: 'Initialize the working directory and download required providers' },
      { cmd: 'terraform plan -out=tfplan', desc: 'Preview all changes and save them to a plan file' },
      { cmd: 'terraform apply tfplan', desc: 'Apply the saved plan — no interactive confirmation prompt' },
      { cmd: 'terraform destroy', desc: 'Destroy all resources managed by this configuration' },
      { cmd: 'terraform import aws_instance.web i-1234567890', desc: 'Import an existing resource into Terraform state' },
      { cmd: 'terraform state list', desc: 'List all resources currently tracked in the state file' },
      { cmd: 'terraform output', desc: 'Print all output values from the current state' },
    ],
  },

  ansible: {
    slug: 'ansible',
    name: 'ANSIBLE',
    sub: 'Automation',
    icon: 'devicon-ansible-plain',
    tagline: 'Automate configuration. No agents. Just SSH and YAML.',
    what: 'Ansible is an open-source automation tool for configuration management, application deployment, and task automation. Unlike Puppet or Chef, Ansible requires no agent installed on managed nodes — it connects over SSH and runs tasks using Python. You write Playbooks in plain YAML that describe the desired state of your systems. Ansible is idempotent: run a playbook ten times and you get the same result every time.',
    benefits: [
      { icon: 'fas fa-plug-circle-xmark', title: 'Agentless',        desc: 'No software to install on managed nodes. Connects over SSH (Linux) or WinRM (Windows). Nothing extra to maintain.' },
      { icon: 'fas fa-file-code',         title: 'Simple YAML',      desc: 'Playbooks read like plain English. Any engineer can follow a task list without learning a complex DSL.' },
      { icon: 'fas fa-equals',            title: 'Idempotent',       desc: 'Running a playbook multiple times produces the same result. Ansible only makes changes when the state differs.' },
      { icon: 'fas fa-puzzle-piece',      title: '3000+ Modules',    desc: 'Built-in modules for managing packages, files, users, services, cloud resources, containers, and more.' },
      { icon: 'fas fa-server',            title: 'Works Anywhere',   desc: 'Configure existing VMs, bare metal, network devices, and cloud instances. No need to rebuild from scratch.' },
      { icon: 'fas fa-lock',              title: 'Ansible Vault',    desc: 'Encrypt secrets directly inside your playbooks. Passwords and API keys stored safely in your Git repository.' },
    ],
    concepts: [
      { term: 'Playbook',   def: 'A YAML file defining a set of plays. Each play targets a group of hosts and runs a list of tasks.' },
      { term: 'Task',       def: 'A single unit of automation: install a package, copy a file, restart a service.' },
      { term: 'Role',       def: 'A reusable, structured set of tasks, variables, templates, and handlers for a specific purpose (e.g. an nginx role).' },
      { term: 'Inventory',  def: 'A list of managed hosts organized into groups. Can be a static file or dynamic (pulled from AWS, GCP).' },
      { term: 'Module',     def: 'Pre-built units Ansible executes on hosts: apt, yum, copy, service, template, file, shell, and many more.' },
      { term: 'Handler',    def: 'A task triggered by a notify directive — typically used to restart a service after a config file changes.' },
      { term: 'Template',   def: 'A Jinja2 file that renders config dynamically using variables. Output differs per host or environment.' },
      { term: 'Vault',      def: 'Ansible\'s built-in encryption. Encrypt entire files or individual values containing secrets.' },
    ],
    commands: [
      { cmd: 'ansible all -m ping -i inventory.ini', desc: 'Ping all hosts in the inventory to verify SSH connectivity' },
      { cmd: 'ansible-playbook site.yml -i inventory.ini', desc: 'Run a playbook against an inventory' },
      { cmd: 'ansible-playbook site.yml --check', desc: 'Dry run — show what would change without making any changes' },
      { cmd: 'ansible-playbook site.yml --tags nginx', desc: 'Run only tasks tagged with "nginx"' },
      { cmd: 'ansible-vault encrypt secrets.yml', desc: 'Encrypt a file containing secrets for safe Git storage' },
      { cmd: 'ansible-playbook site.yml -e "env=production"', desc: 'Pass extra variables at runtime' },
    ],
  },

  linux: {
    slug: 'linux',
    name: 'LINUX',
    sub: 'Foundation',
    icon: 'devicon-linux-plain',
    tagline: 'The OS that runs the internet. Learn it deeply.',
    what: 'Linux is the operating system powering over 90% of servers, every Android device, all major cloud providers, and every container you\'ve ever run. For DevOps engineers, Linux is not optional — it is the foundation everything else is built on. You need to navigate the filesystem, manage processes, configure networking, control permissions, debug services, and write shell scripts. A weak understanding of Linux is a hard ceiling on your DevOps career.',
    benefits: [
      { icon: 'fas fa-dollar-sign',     title: 'Free & Open Source', desc: 'No licensing cost. Source code open for inspection and modification. Community-driven, vendor-neutral.' },
      { icon: 'fas fa-shield-halved',   title: 'Stable & Secure',    desc: 'Servers run for years without reboots. Fine-grained permission model. Security patches available immediately.' },
      { icon: 'fas fa-box-open',        title: 'Package Management', desc: 'apt, yum, dnf, apk — install, update, and remove software consistently across all your systems.' },
      { icon: 'fas fa-terminal',        title: 'Scripting Power',    desc: 'Bash, pipes, redirects, cron jobs. Automate anything from the command line with composable tools.' },
      { icon: 'fas fa-network-wired',   title: 'SSH & Remote Access', desc: 'Connect to any server securely from anywhere. The primary interface for managing production systems.' },
      { icon: 'fas fa-layer-group',     title: 'Runs Everything',    desc: 'Containers, VMs, web servers, databases, Kubernetes nodes — all run on Linux. Master the OS, master the stack.' },
    ],
    concepts: [
      { term: 'Filesystem Hierarchy', def: '/etc (config), /var (variable data), /usr (programs), /proc (process info), /tmp (temporary files).' },
      { term: 'Permissions',          def: 'Owner, Group, Others. Read (r=4), Write (w=2), Execute (x=1). Managed with chmod and chown.' },
      { term: 'Processes',            def: 'Every running program is a process with a PID. Manage with ps, top, htop, kill, and systemctl.' },
      { term: 'Systemd',              def: 'The init system and service manager on modern Linux. Start, stop, enable, disable, and inspect services.' },
      { term: 'Cron',                 def: 'Schedule recurring tasks. Edit with crontab -e. Format: minute hour day month weekday command.' },
      { term: 'Pipes & Redirects',    def: 'Chain commands with |. Redirect stdout with > (overwrite) or >> (append). Redirect stderr with 2>.' },
      { term: 'Package Manager',      def: 'apt (Debian/Ubuntu), yum/dnf (RHEL/CentOS), apk (Alpine). Install and manage software dependencies.' },
      { term: 'SSH',                  def: 'Secure Shell. Connect with ssh user@host. Use key-based auth in production — never passwords.' },
    ],
    commands: [
      { cmd: 'grep -rn "ERROR" /var/log/', desc: 'Recursively search for "ERROR" across all log files' },
      { cmd: 'find /app -name "*.conf" -mtime -1', desc: 'Find config files modified in the last 24 hours' },
      { cmd: 'ss -tulnp', desc: 'Show all listening ports and the processes that own them' },
      { cmd: 'systemctl status nginx && journalctl -u nginx -f', desc: 'Check service status and stream its logs' },
      { cmd: 'chmod 600 ~/.ssh/id_rsa && chmod 700 ~/.ssh/', desc: 'Fix SSH key file permissions to avoid connection rejections' },
      { cmd: 'ps aux --sort=-%mem | head -10', desc: 'List the top 10 most memory-intensive processes' },
      { cmd: 'df -h && du -sh /var/log/*', desc: 'Check disk usage and individual log directory sizes' },
    ],
  },

  monitoring: {
    slug: 'monitoring',
    name: 'MONITORING',
    sub: 'Observability',
    icon: 'devicon-prometheus-original',
    iconStyle: { color: '#e6522c' },
    tagline: 'If you can\'t measure it, you can\'t fix it.',
    what: 'Monitoring and observability is the practice of instrumenting your systems to understand their behavior in production. The three pillars are Metrics (numeric measurements over time), Logs (timestamped event records), and Traces (request paths across services). Without monitoring you find out about problems from angry users. With proper observability, you detect anomalies before users notice and find root causes in minutes.',
    benefits: [
      { icon: 'fas fa-bell',         title: 'Proactive Alerting',  desc: 'Set thresholds on key metrics. PagerDuty or Slack alerts fire before users ever report a problem.' },
      { icon: 'fas fa-gauge-high',   title: 'SLO Tracking',        desc: 'Define Service Level Objectives. Track error rate and latency against your actual uptime commitments.' },
      { icon: 'fas fa-database',     title: 'Capacity Planning',   desc: 'Track resource trends over weeks and months. Know before you run out of disk, CPU, or database connections.' },
      { icon: 'fas fa-magnifying-glass', title: 'Root Cause Analysis', desc: 'Correlate a latency spike with a deploy or a CPU spike with a cron job. Find the cause, not just the symptom.' },
      { icon: 'fas fa-users',        title: 'Real User Impact',    desc: 'Measure actual user experience — not just whether the server is running, but whether responses are fast enough.' },
      { icon: 'fas fa-chart-line',   title: 'Trend Detection',     desc: 'Spot gradual degradation before it becomes an outage: memory leaks, growing query times, creeping error rates.' },
    ],
    concepts: [
      { term: 'Metrics',      def: 'Numeric measurements over time: CPU %, request rate (req/s), error rate, latency (p50, p95, p99).' },
      { term: 'Logs',         def: 'Timestamped event records. Centralize with Loki, ELK Stack, or CloudWatch Logs for querying at scale.' },
      { term: 'Traces',       def: 'Track a single request end-to-end across multiple microservices. Identify exactly where latency is introduced.' },
      { term: 'Prometheus',   def: 'Open-source metrics time-series database. Scrapes targets via HTTP on a configurable interval.' },
      { term: 'Grafana',      def: 'Visualization layer. Build dashboards on Prometheus, Loki, CloudWatch, and many other data sources.' },
      { term: 'Alertmanager', def: 'Routes Prometheus alerts to Slack, PagerDuty, or email. Handles deduplication, grouping, and silencing.' },
      { term: 'SLI / SLO / SLA', def: 'SLI: what you measure. SLO: your internal target (e.g. 99.9% uptime). SLA: the contract with customers.' },
      { term: 'Cardinality',  def: 'The number of unique label combinations in a metric. High cardinality can break Prometheus — design labels carefully.' },
    ],
    commands: [
      { cmd: 'curl http://localhost:9090/api/v1/query?query=up', desc: 'Query Prometheus HTTP API for scrape target health' },
      { cmd: 'rate(http_requests_total[5m])', desc: 'PromQL: calculate per-second request rate over a 5-minute window' },
      { cmd: 'histogram_quantile(0.99, rate(http_duration_seconds_bucket[5m]))', desc: 'PromQL: calculate the p99 latency from a histogram metric' },
      { cmd: 'kubectl top pods --sort-by=cpu -n production', desc: 'Show CPU usage of all pods in the production namespace' },
      { cmd: 'logcli query \'{app="nginx"}\' --since=1h', desc: 'Query Loki logs for the nginx application from the last hour' },
    ],
  },

  scripting: {
    slug: 'scripting',
    name: 'SCRIPTING',
    sub: 'Automation',
    icon: 'fas fa-terminal',
    tagline: 'Stop doing it manually. Write it once, run it forever.',
    what: 'Scripting is the glue that holds DevOps together. Bash scripts automate server tasks, Python orchestrates complex workflows, and shell one-liners transform data in pipelines. A DevOps engineer who cannot write a script is forced to do repetitive work manually — and humans make mistakes at 2am during an incident. Scripting skills compound: every automated task is one fewer thing you have to remember, and one more thing your entire team benefits from.',
    benefits: [
      { icon: 'fas fa-ban',          title: 'Eliminate Manual Work', desc: 'Write a script once. Run it a thousand times. Never forget a step or make a typo in a production command again.' },
      { icon: 'fas fa-repeat',       title: 'Reproducible',          desc: 'Scripts document exact steps. Another engineer runs the same script and gets the identical result every time.' },
      { icon: 'fas fa-link',         title: 'Tool Integration',      desc: 'Scripts connect kubectl, aws CLI, jq, curl, and your CI system into a single automated workflow.' },
      { icon: 'fas fa-bolt',         title: 'Speed',                 desc: 'What takes 30 minutes manually takes 30 seconds with a script. Faster deployments, faster incident recovery.' },
      { icon: 'fas fa-clock',        title: 'Scheduled Automation',  desc: 'Cron jobs run your scripts on a schedule. Nightly backups, daily reports, hourly health checks — unattended.' },
      { icon: 'fas fa-people-group', title: 'Team Multiplier',       desc: 'A well-written script lets a junior engineer do what previously required a senior. Knowledge encoded in code.' },
    ],
    concepts: [
      { term: 'Exit Code',          def: '0 = success, non-zero = failure. Use set -e to exit immediately on error. Check with $? or in conditionals.' },
      { term: 'Pipes',              def: 'Chain commands: cmd1 | cmd2. The output of the left becomes the input of the right. Combine simple tools powerfully.' },
      { term: 'Variables',          def: 'NAME="value". Reference with $NAME. Always quote variables in strings to handle spaces: "$NAME".' },
      { term: 'Loops',              def: 'for f in *.log; do gzip "$f"; done — or while read line; do ...; done < input.txt.' },
      { term: 'Functions',          def: 'Group reusable logic. Call by name. Access arguments as $1, $2. Return values via echo or exit code.' },
      { term: 'Stdin/Stdout/Stderr', def: 'Three data streams: 0 (input), 1 (output), 2 (errors). Redirect independently: 2>/dev/null.' },
      { term: 'Shebang',            def: '#!/usr/bin/env bash at the top of every script. Tells the OS which interpreter to use.' },
      { term: 'jq',                 def: 'Command-line JSON processor. Essential for parsing kubectl output, API responses, and config files in scripts.' },
    ],
    commands: [
      { cmd: '#!/usr/bin/env bash\nset -euo pipefail', desc: 'Safe script header: exit on error, treat unset vars as errors, catch pipe failures' },
      { cmd: 'for pod in $(kubectl get pods -o name); do\n  echo "Restarting $pod"\n  kubectl delete "$pod"\ndone', desc: 'Loop over all pods and restart them one by one' },
      { cmd: 'kubectl get pods -o json | jq \'.items[].metadata.name\'', desc: 'Parse kubectl JSON output and extract pod names with jq' },
      { cmd: 'aws ec2 describe-instances | jq -r \'.Reservations[].Instances[] | [.InstanceId,.State.Name] | @tsv\'', desc: 'List all EC2 instances with their states in TSV format' },
      { cmd: 'trap \'echo "Failed on line $LINENO"\' ERR', desc: 'Trap errors and print the exact line number that failed' },
      { cmd: 'if ! command -v kubectl &>/dev/null; then\n  echo "kubectl not installed"\n  exit 1\nfi', desc: 'Check if a required command exists before running the rest of the script' },
    ],
  },
}
